### ISSUE TITLE
Bad error on old agg.filter syntax

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#4770] opened 2018-11-13 19:40 UTC
```
mt = get_gnomad_data(data_type, release_samples=True, release_annotations=True)
cut_dict = {'pop': hl.agg.counter(hl.agg.filter(hl.is_defined(mt.meta.pop), mt.meta.pop)),
            'subpop': hl.agg.collect_as_set(
                hl.agg.filter(hl.is_defined(mt.meta.subpop) & hl.is_defined(mt.meta.pop),
                              hl.struct(subpop=mt.meta.subpop, pop=mt.meta.pop)))
            }
cut_data = mt.aggregate_cols(hl.struct(**cut_dict))
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-0d2fea45d693>", line 1, in <module>
    cut_dict = {'pop': hl.agg.counter(hl.agg.filter(hl.is_defined(mt.meta.pop), mt.meta.pop)),
  File "<decorator-gen-998>", line 2, in filter
  File "/Users/konradk/hail/hail/python/hail/typecheck/check.py", line 559, in wrapper
    args_, kwargs_ = check_all(__original_func, args, kwargs, checkers, is_method=is_method)
  File "/Users/konradk/hail/hail/python/hail/typecheck/check.py", line 487, in check_all
    args_.append(checker.check(arg, name, arg_name))
  File "/Users/konradk/hail/hail/python/hail/expr/aggregators/aggregators.py", line 26, in check
    assert(len(x._ir.search(lambda node: isinstance(node, BaseApplyAggOp))) != 0)
AssertionError
```

**Comment by danking** [comment] 2019-01-09 20:39
So the issue is that we used to have `filter` and `explode` inside of aggregations (like `counter` and `collect_as_set`). Now they're placed outside of these operations. There was [a forum post](https://discuss.hail.is/t/breaking-change-redesign-of-aggregator-interface/701) announcing this breaking change.

The above to examples should instead be written as:

```
cut_dict = {'pop': hl.agg.filter(hl.is_defined(mt.meta.pop), hl.agg.counter(mt.meta.pop)),
            'subpop': hl.agg.filter(hl.is_defined(mt.meta.subpop) & hl.is_defined(mt.meta.pop),
                hl.agg.collect_as_set(hl.struct(subpop=mt.meta.subpop, pop=mt.meta.pop)))
            }
```

The fix for this issue is to change the assertion into an `if` with a `raise` of an error message, probably one that references that discuss post.

**Closed** 2019-01-10 19:43 UTC
