### ISSUE TITLE
AttributeError: module 'hail' has no attribute 'expr'

### ISSUE THREAD

**Issue by pyousefi** [hail-is/hail#6762] opened 2019-07-30 12:32 UTC
Relevant installed library versions:
hail==0.2.18
numpy==1.17.0
pandas==0.23.4
pyspark==2.4.1
scipy==1.3.0

Code ran:
```
import hail as hl

Stack trace:
AttributeError: module 'hail' has no attribute 'expr'

AttributeError                            Traceback (most recent call last)
in engine
----> 1 import hail as hl

/home/cdsw/.local/lib/python3.6/site-packages/hail/__init__.py in <module>()
     29 from .expr import *
     30 from .genetics import *
---> 31 from .methods import *
     32 from . import genetics
     33 from . import methods

/home/cdsw/.local/lib/python3.6/site-packages/hail/methods/__init__.py in <module>()
      4     import_plink, read_matrix_table, read_table, get_vcf_metadata, import_vcf, import_vcfs, \
      5     index_bgen, import_matrix_table
----> 6 from .statgen import skat, identity_by_descent, impute_sex, \
      7     genetic_relatedness_matrix, realized_relationship_matrix, pca, \
      8     hwe_normalized_pca, pc_relate, split_multi, filter_alleles, filter_alleles_hts, \

/home/cdsw/.local/lib/python3.6/site-packages/hail/methods/statgen.py in <module>()
      5 
      6 import hail as hl
----> 7 import hail.expr.aggregators as agg
      8 from hail.expr.expressions import *
      9 from hail.expr.types import *

AttributeError: module 'hail' has no attribute 'expr'
```

**Comment by tpoterba** [comment] 2019-07-30 13:50
We've hit issues like this on some installations of Python, but I still have no idea what is the root cause inside Python. It looks like sometimes the submodule `bar` needs to be in the `__all__` of `foo` to import like as `import foo.bar.baz as bazz`, and sometimes not.

**Comment by tpoterba** [comment] 2019-07-31 18:13
I think we can fix this by adding `expr` to the __all__ in the __init__.py, or by changing these imports.

**Comment by tpoterba** [comment] 2019-08-19 09:22
@pyousefi could you help me replicate this? What system are you using, and which specific Python installation?

**Comment by hammer** [comment] 2019-09-19 19:04
I think the issue is that I used `pip3` to install `hail`, following the docs. Unfortunately, `conda` only installs `pip` into the `hail` environment, not `pip3`, so I was using my system-wide `pip3` to install `hail`.  When I use `pip` to install `hail`, everything works fine. Maybe just update the docs to use `pip` instead of `pip3`?

**Comment by danking** [comment] 2019-09-19 19:14
I'll update them to run `python3 -m pip`

**Comment by hammer** [comment] 2019-09-19 19:14
Sent a PR over with the doc fix https://github.com/hail-is/hail/pull/7094. I did not claim it closes this issue as @pyousefi may be hitting another issue.

**Comment by danking** [comment] 2019-09-19 19:15
Thanks

**Comment by tpoterba** [comment] 2019-09-19 19:43
Hmmmm, I still don't totally understand why we're hitting this specific import error. The system pip should still be able to install and run hail, I think -- I'd expect either an import error saying that `hail` cannot be found (if it's installed somewhere not on the Python path), or success.

I still want to replicate in a docker, will report back.

**Comment by tpoterba** [comment] 2020-04-14 14:39
I couldn't replicate this. Closing until people hit it again.

**Closed by tpoterba** 2020-04-14 14:39 UTC

**Comment by PoisonAlien** [comment] 2022-09-29 14:18
Hello developers,
Sorry for resurrecting the issue. I have the same problem with a different Error.

```
conda create -n hail2
conda activate hail2
conda install -c bioconda hail
pip install gnomad
```

Installation has no issues. But below command throws error. This is the same on two different machines that I have tried so far. Removing conda env, or changing env location, has not helped me so far.

```
import hail
from gnomad.sample_qc.ancestry import assign_population_pcs

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/datadir1/conda_envs_AMT/hail2/lib/python3.7/site-packages/gnomad/sample_qc/ancestry.py", line 9, in <module>
    from gnomad.utils.filtering import filter_to_autosomes
  File "/datadir1/conda_envs_AMT/hail2/lib/python3.7/site-packages/gnomad/utils/filtering.py", line 9, in <module>
    from gnomad.resources.resource_utils import DataException
  File "/datadir1/conda_envs_AMT/hail2/lib/python3.7/site-packages/gnomad/resources/__init__.py", line 3, in <module>
    from .resource_utils import *
  File "/datadir1/conda_envs_AMT/hail2/lib/python3.7/site-packages/gnomad/resources/resource_utils.py", line 162, in <module>
    class VariantDatasetResource(BaseResource):
  File "/datadir1/conda_envs_AMT/hail2/lib/python3.7/site-packages/gnomad/resources/resource_utils.py", line 173, in VariantDatasetResource
    def vds(self, force_import: bool = False) -> hl.vds.VariantDataset:
AttributeError: module 'hail' has no attribute 'vds'
```

Could anyone please recommend me how to circumvent this?
Thanks for the amazing package.

**Comment by tpoterba** [comment] 2022-09-29 14:21
Hail doesn't have a conda package -- the bioconda package there was not uploaded by the Hail Team (could even be malware -- we don't know). It's certainly a very old version.

If you install Hail with pip, you should pick up the latest version 0.2.100 and have access to hl.vds, which is somewhat recent functionality.

**Comment by PoisonAlien** [comment] 2022-09-29 14:38
Thank you for the quick reply. Indeed it works now.

**Comment by PoisonAlien** [comment] 2022-09-29 15:00
Hi Tim,
Sorry for the bother again. I am following this short tutorial as described [here](https://gnomad.broadinstitute.org/news/2021-09-using-the-gnomad-ancestry-principal-components-analysis-loadings-and-random-forest-classifier-on-your-dataset/).

The code snippet was working properly with earlier. Now that I have installed hail from pip, I have this error while running RF model.

```
ht, rf_model = assign_population_pcs(
...     ht,
...     pc_cols=ht.scores,
...     fit=fit,
... )

2022-09-29 14:55:46 Hail: INFO: Coerced sorted dataset              (0 + 1) / 1]
INFO (gnomad.sample_qc.ancestry 224): Found the following sample count after population assignment: sas: 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/bioinfoRD/ARCdata/Projects_AMT/conda_envs/hail/lib/python3.10/site-packages/gnomad/sample_qc/ancestry.py", line 235, in assign_population_pcs
    min_assignment_prob=min_prob, error_rate=error_rate
UnboundLocalError: local variable 'error_rate' referenced before assignment
```

Could you please suggest what might be happening here?

**Comment by tpoterba** [comment] 2022-09-29 15:19
This looks like a bug in the gnomAD assign_population_pcs method. You might post an issue there.
