### ISSUE TITLE
Very stringent python dependencies

### ISSUE THREAD

**Issue by Hoeze** [hail-is/hail#7299] opened 2019-10-15 11:30 UTC
Hi, I just tried installing hail with pip but it has very stringent version dependencies.
For example, it requires [pandas>0.22,<0.24](https://github.com/hail-is/hail/blob/04344d214361daede1417e74b206b739eff9ae87/hail/python/requirements.txt#L10) which causes a `pip install hail` to downgrade my pandas version.

Would it be feasible to remove all those `<0.x` in the dependencies?
Usually, new versions of e.g. pandas introduce less problems to the user than downgrades caused by pip packages (`pip` does not resolve dependencies in contrast to e.g. `conda`).

**Comment by johnc1231** [comment] 2019-10-15 12:11
Sometimes new versions of packages introduce breaking changes, which is why we have version pins. I'll look at pandas shortly and see if there's any reason we can't update the upper bound on that range though

**Comment by tpoterba** [comment] 2019-10-15 12:17
Python versioning is a huge problem. Basically every time we have used unbounded dependency versions, we've gotten burned (some package updates and now Hail is broken for anyone who tries to install it).

John could find out that 0.24 is supported, but then we'd have to pin at `<0.25`, so this doesn't solve the problem generally.

I think we're also feeling quite sour on conda at the moment as well. In particular, I had to fix the [environment.yml for LDSC](https://github.com/bulik/ldsc/pull/168) because **recent versions of conda removed scipy==0.18 from their registry**.

**Comment by Hoeze** [comment] 2019-10-15 12:48
My main motivation is that I can use up-to-date versions of NumPy, SciPy and Pandas.

> I think we're also feeling quite sour on conda at the moment as well. In particular, I had to fix the [environment.yml for LDSC](https://github.com/bulik/ldsc/pull/168) because **recent versions of conda removed scipy==0.18 from their registry**.

Wow, that's bad. I did not know conda removes old packages.

Are you using some continuous integration?
We are solving these issues by some policy that pull requests have to pass CI building. 
If there is a new version of e.g. Pandas, CI will install it when somebody pushes a commit.
In case the new package version breaks something, CI fails and we get a notification to fix it.

This way, we can in general keep up to date with the latest package versions and only rise the minimum version number of dependencies.

**Comment by tpoterba** [comment] 2019-10-15 13:13
> My main motivation is that I can use up-to-date versions of NumPy, SciPy and Pandas.

Yeah, I'm sympathetic to this. Our current pinned-version approach is partially a [over-]reaction to builds breaking without any internal change, especially because many new Hail users are also new Python users and not capable of debugging Python dependency hell.

> Are you using some continuous integration?

We do use CI, but I'm not exactly sure what you're proposing. An automatic find-the-latest-version-that-works step? It's true that if we were to use unpinned versions, our CI would start failing if a package introduces a breaking change, and we can fix it. However, I think that's too late -- now all old Hail versions will break from fresh installs! I feel that reproducibility demands we pin versions.

**Comment by tpoterba** [comment] 2019-10-15 13:14
(that's not to say we shouldn't do dependency audits every few months, bumping the pinned version to latest)

**Comment by Hoeze** [comment] 2019-10-15 13:22
I'd propose to do an implicit dependency audit every time you push a new commit.

You can still pin versions on published packages, but use unpinned dependencies for CI.

**Comment by tpoterba** [comment] 2019-10-15 13:51
> I'd propose to do an implicit dependency audit every time you push a new commit.

> You can still pin versions on published packages, but use unpinned dependencies for CI testing.

I think our only option here would be to test twice -- once with the major versions  we explicitly depend on, and once with unbounded versions. I don't really like this model, since it basically couples breaking changes in other tools to Hail commits, which isn't how it actually works.

I'd much prefer a weekly cron job that tries to update dependencies, I think, but that thing isn't trivial to build.

**Comment by johnc1231** [comment] 2019-10-15 14:18
Updating pandas version in #7301 to (partially) address this issue. There's still some larger questions about not pinning specific versions in the first place.

**Comment by tpoterba** [comment] 2020-04-14 20:33
Going to close this because we're not going to take any action on it in the immediate future.

**Closed by tpoterba** 2020-04-14 20:33 UTC
