### ISSUE TITLE
varspark.hail unable to be imported due to SparkBackend error

### ISSUE THREAD

**Issue by chrysania** [hail-is/hail#12859] opened 2023-04-10 06:30 UTC
### What happened?

- Tried to import VariantSpark version 0.5.2 into a Google Colab notebook running Python 3.9.16, with Hail version 0.2.112 and Apache Spark version 3.3.2. When trying to import VariantSpark, the following error occurred:
`import hail as hl
import varspark.hail as vshl
vshl.init()`
`using variant-spark jar at '/usr/local/lib/python3.9/dist-packages/varspark/jars/variant-spark_2.12-0.5.2-all.jar'
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-6-3d2ff0083f18>](https://localhost:8080/#) in <cell line: 3>()
      1 import hail as hl
      2 import varspark.hail as vshl
----> 3 vshl.init()

4 frames
<decorator-gen-1907> in init(sc, app_name, master, local, log, quiet, append, min_block_size, branching_factor, tmp_dir, default_reference, idempotent, global_seed, spark_conf, skip_logging_configuration, local_tmpdir, _optimizer_iterations, backend, driver_cores, driver_memory, worker_cores, worker_memory, gcs_requester_pays_configuration, regions)

<decorator-gen-1909> in init_spark(sc, app_name, master, local, log, quiet, append, min_block_size, branching_factor, tmp_dir, default_reference, idempotent, global_seed, spark_conf, skip_logging_configuration, local_tmpdir, _optimizer_iterations, gcs_requester_pays_configuration)

[/usr/local/lib/python3.9/dist-packages/hail/context.py](https://localhost:8080/#) in init_spark(sc, app_name, master, local, log, quiet, append, min_block_size, branching_factor, tmp_dir, default_reference, idempotent, global_seed, spark_conf, skip_logging_configuration, local_tmpdir, _optimizer_iterations, gcs_requester_pays_configuration)
    425     app_name = app_name or 'Hail'
    426     gcs_requester_pays_project, gcs_requester_pays_buckets = convert_gcs_requester_pays_configuration_to_hadoop_conf_style(gcs_requester_pays_configuration)
--> 427     backend = SparkBackend(
    428         idempotent, sc, spark_conf, app_name, master, local, log,
    429         quiet, append, min_block_size, branching_factor, tmpdir, local_tmpdir,

TypeError: SparkBackend__init__() got an unexpected keyword argument 'gcs_requester_pays_project'`

- Hail was able to initialize by itself
`import hail as hl
print(hl.version())
hl.init()`
`0.2.112-31ceff2fb5fd
Running on Apache Spark version 3.3.2
SparkUI available at http://57ba6dc5f4a9:4040/
Welcome to
     __  __     <>__
    / /_/ /__  __/ /
   / __  / _ `/ / /
  /_/ /_/\_,_/_/_/   version 0.2.112-31ceff2fb5fd
LOGGING: writing to /content/hail-20230410-0617-0.2.112-31ceff2fb5fd.log`

### Version

0.2.112

### Relevant log output

```shell
using variant-spark jar at '/usr/local/lib/python3.9/dist-packages/varspark/jars/variant-spark_2.12-0.5.2-all.jar'
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-3d2ff0083f18> in <cell line: 3>()
      1 import hail as hl
      2 import varspark.hail as vshl
----> 3 vshl.init()

4 frames
<decorator-gen-1907> in init(sc, app_name, master, local, log, quiet, append, min_block_size, branching_factor, tmp_dir, default_reference, idempotent, global_seed, spark_conf, skip_logging_configuration, local_tmpdir, _optimizer_iterations, backend, driver_cores, driver_memory, worker_cores, worker_memory, gcs_requester_pays_configuration, regions)

<decorator-gen-1909> in init_spark(sc, app_name, master, local, log, quiet, append, min_block_size, branching_factor, tmp_dir, default_reference, idempotent, global_seed, spark_conf, skip_logging_configuration, local_tmpdir, _optimizer_iterations, gcs_requester_pays_configuration)

/usr/local/lib/python3.9/dist-packages/hail/context.py in init_spark(sc, app_name, master, local, log, quiet, append, min_block_size, branching_factor, tmp_dir, default_reference, idempotent, global_seed, spark_conf, skip_logging_configuration, local_tmpdir, _optimizer_iterations, gcs_requester_pays_configuration)
    425     app_name = app_name or 'Hail'
    426     gcs_requester_pays_project, gcs_requester_pays_buckets = convert_gcs_requester_pays_configuration_to_hadoop_conf_style(gcs_requester_pays_configuration)
--> 427     backend = SparkBackend(
    428         idempotent, sc, spark_conf, app_name, master, local, log,
    429         quiet, append, min_block_size, branching_factor, tmpdir, local_tmpdir,

TypeError: SparkBackend__init__() got an unexpected keyword argument 'gcs_requester_pays_project'
```

**Comment by danking** [comment] 2023-04-10 19:26
This is caused by VariantSpark monkey patching Hail. I've asked them to [stop doing this](https://github.com/aehrc/VariantSpark/issues/228).

**Comment by danking** [comment] 2023-04-12 11:57
This is fixed in newer versions of VariantSpark.

**Closed by danking** 2023-04-12 11:57 UTC
