### ISSUE TITLE
[docker] hailgenetics/hail should have tags for each supported Python version

### ISSUE THREAD

**Issue by danking** [hail-is/hail#13162] opened 2023-06-09 15:45 UTC
### What happened?

e.g. https://hail.zulipchat.com/#narrow/stream/223457-Hail-Batch-support/topic/Error.20in.20QoB.3A.20unknown.20opcode/near/364895723

We should provide tags like `hailgenetics/hail:0.2.117-py3.8` or something. Maybe look a Tensorflow or PyTorch or pyspark for naming inspiration? I think we should still provide `hailgenetics/hail:0.2.117` with our most well-tested version of Python.

### Version

0.2.117

**Comment by daniel-goldstein** [comment] 2023-09-18 12:18
Closing as a duplicate of #13558 but #13558 has some more information.

**Closed by daniel-goldstein** 2023-09-18 12:18 UTC
Labels: new-feature
