### ISSUE TITLE
Zstd bgen error

### ISSUE THREAD

**Issue by barneyhill** [hail-is/hail#12608] opened 2023-01-19 16:21 UTC
Hail Version: 0.2.108

Running the line w/ Zstd compressed UKB bgen files:
`ht = hl.experimental.pc_project(
    mt.GT,
    loadings_ht.loadings,
    loadings_ht.pca_af,
)
`
I get the error at the end of spark execution: 
`Exception in thread "map-output-dispatcher-0" Exception in thread "map-output-dispatcher-1" java.lang.UnsatisfiedLinkError: com.github.luben.zstd.ZstdOutputStreamNoFinalizer.recommendedCOutSize()J
`
(full error attached)
[error.txt](https://github.com/hail-is/hail/files/10458606/error.txt)

Any ideas?
Many Thanks,
Barney

**Comment by danking** [comment] 2023-03-02 21:48
Hi @barneyhill ! Sorry for the high latency. We don't do a great job of watching GitHub issues. In the future a post on https://discuss.hail.is will get a faster response.

This sounds like a versioning issue. What is your environment? What version of Spark do you have?

This appears to be a fairly common issue that might be cause by class path issues or native library loading issues.:
1. https://github.com/luben/zstd-jni/issues/190
2. https://github.com/luben/zstd-jni/issues/60

**Comment by danking** [comment] 2023-03-02 21:51
Sounds like there might be particular issues if your environment is making your temporary directory not writable or mounted it with `noexec`.

**Comment by danking** [comment] 2023-03-07 18:50
Hey @barneyhill , were you able to resolve this issue?

**Comment by danking** [comment] 2023-03-13 21:40
Closing due to lack of reproducible example.

For future users who find themselves here: I'm fairly sure the issue is the noexec status of the Spark temporary directory.

**Closed by danking** 2023-03-13 21:40 UTC
