### ISSUE TITLE
No plots on hail (conda env on a MacOS)

### ISSUE THREAD

**Issue by alanmejiamaza** [hail-is/hail#12717] opened 2023-02-20 16:05 UTC
### What happened?

Hi,
I am on a macOS Ventura and I have successfully installed hail (v 0.2.109) on a conda env. Everything seems to run properly, except that I don't get any plots. Bokeh was installed in the env, v1.4.0., pysark =3.13 and scala=2.11.8 are some relevant packages that may contribute to this issue.

When starting Hail, this is the output I get:

2023-02-20 11:07:38.798 WARN  NativeCodeLoader:60 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
Running on Apache Spark version 3.1.3
SparkUI available at http://amaru-2.local:4040
Welcome to
     __  __     <>__
    / /_/ /__  __/ /
   / __  / _ `/ / /
  /_/ /_/\_,_/_/_/   version 0.2.109-b71b065e4bb6
LOGGING: writing to /Users/alanmejiamaza/hail-20230220-1107-0.2.109-b71b065e4bb6.log

It seems to be that the issue comes from the spark version?  which is the correct spark version for a conda env on a mac? I have followed the tutorials and seemed to work fine except for the plots. I don't have any output when invoking commands for plots.

Can anyone tell me the specific versions needed to run all Hail properties?

Thanks

### Version

0.2.109

**Comment by danking** [comment] 2023-03-02 21:54
Hi @alanmejiamaza ,

Just to be clear, you did `pip install hail` and then you opened a notebook and ran something like:
```
import hail as hl
hl.init()
from hail.plot import show
from pprint import pprint
hl.plot.output_notebook()
ht = hl.utils.range_table(1000)
ht = mt.annotate(DP = hl.rand_unif(0, 100))
p = hl.plot.histogram(ht.DP, range=(0,30), bins=30, title='DP Histogram', legend='DP')
show(p)
```
And the plot didn't appear? Did you get a message saying "BokehJS 1.4.0 successfully loaded."? What version of Jupyter are you using? What web browser are you using?

**Comment by danking** [comment] 2023-03-07 18:49
Hey @alanmejiamaza, could you reply to my message above? I can't replicate the issue without more information.

**Comment by danking** [comment] 2023-03-13 21:39
Closing due to lack of reproduction. Please feel free to comment and ping me if you can provide more details!

**Closed by danking** 2023-03-13 21:39 UTC
