### ISSUE TITLE
Error compiling HAIL on Mac

### ISSUE THREAD

**Issue by jjfarrell** [hail-is/hail#1274] opened 2017-01-20 13:51 UTC
Getting the following errors when compiling on a Mac. Any suggestions?

 ./gradlew shadowJar 
:compileJava UP-TO-DATE
:nativeLib
(cd libsimdpp-2.0-rc2 && cmake .)
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/farrell/github/hail/src/main/c/libsimdpp-2.0-rc2
mkdir -p lib/darwin
c++ -fvisibility=hidden -dynamiclib -O3 -march=native -g -std=c++11 -Ilibsimdpp-2.0-rc2  ibs.cpp -o lib/darwin/libibs.dylib
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:23:no such instruction: `vmovd %xmm0, %rax'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:38:no such instruction: `vpextrq $1, %xmm0,%rax'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:79:no such instruction: `vpcmpeqd %xmm5, %xmm5,%xmm5'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:96:no such instruction: `vpxor %xmm1, %xmm0,%xmm1'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:114:no such instruction: `vpxor %xmm5, %xmm1,%xmm1'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:135:no such instruction: `vpand %xmm3, %xmm2,%xmm3'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:150:no such instruction: `vpsrlq $1, %xmm1,%xmm0'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:167:no such instruction: `vpxor %xmm5, %xmm3,%xmm3'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:193:no such instruction: `vpor LC1(%rip), %xmm3,%xmm3'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:212:no such instruction: `vpand %xmm1, %xmm0,%xmm4'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:225:no such instruction: `vpandn %xmm4, %xmm3,%xmm4'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:241:no such instruction: `vmovd %xmm4, %rax'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:255:no such instruction: `vpxor %xmm1, %xmm0,%xmm2'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:277:no such instruction: `vpandn %xmm2, %xmm3,%xmm2'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:293:no such instruction: `vpextrq $1, %xmm4,%rax'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:318:no such instruction: `vpor %xmm1, %xmm0,%xmm1'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:335:no such instruction: `vpxor %xmm5, %xmm1,%xmm1'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:356:no such instruction: `vmovd %xmm2, %rax'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:371:no such instruction: `vpandn %xmm1, %xmm3,%xmm3'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:390:no such instruction: `vpextrq $1, %xmm2,%rax'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:415:no such instruction: `vmovd %xmm3, %rax'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:429:no such instruction: `vpextrq $1, %xmm3,%rax'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:469:no such instruction: `vpxor LC1(%rip), %xmm0,%xmm0'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:482:no such instruction: `vpsrlq $1, %xmm0,%xmm1'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:496:no such instruction: `vpor %xmm0, %xmm1,%xmm0'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:533:no such instruction: `vmovdqa LC1(%rip), %xmm2'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:554:no such instruction: `vpcmpeqd %xmm5, %xmm5,%xmm5'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:582:no such instruction: `vpxor %xmm1, %xmm2,%xmm6'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:595:no such instruction: `vpsrlq $1, %xmm6,%xmm3'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:609:no such instruction: `vpor %xmm6, %xmm3,%xmm6'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:629:no such instruction: `vpxor %xmm0, %xmm2,%xmm3'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:647:no such instruction: `vpxor %xmm1, %xmm0,%xmm0'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:664:no such instruction: `vpsrlq $1, %xmm3,%xmm4'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:685:no such instruction: `vpxor %xmm5, %xmm0,%xmm0'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:701:no such instruction: `vpsrlq $1, %xmm0,%xmm1'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:719:no such instruction: `vpor %xmm3, %xmm4,%xmm3'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:741:no such instruction: `vpand %xmm6, %xmm3,%xmm3'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:760:no such instruction: `vpand %xmm0, %xmm1,%xmm4'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:782:no such instruction: `vpxor %xmm5, %xmm3,%xmm3'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:802:no such instruction: `vpor %xmm2, %xmm3,%xmm2'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:819:no such instruction: `vpandn %xmm4, %xmm2,%xmm4'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:835:no such instruction: `vmovd %xmm4, %rax'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:849:no such instruction: `vpxor %xmm0, %xmm1,%xmm3'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:865:no such instruction: `vpandn %xmm3, %xmm2,%xmm3'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:883:no such instruction: `vpor %xmm0, %xmm1,%xmm0'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:902:no such instruction: `vpextrq $1, %xmm4,%rax'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:923:no such instruction: `vmovd %xmm3, %rax'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:941:no such instruction: `vpxor %xmm5, %xmm0,%xmm0'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:967:no such instruction: `vpandn %xmm0, %xmm2,%xmm2'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:983:no such instruction: `vpextrq $1, %xmm3,%rax'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:1012:no such instruction: `vmovd %xmm2, %rax'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:1026:no such instruction: `vpextrq $1, %xmm2,%rax'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:1059:no such instruction: `vmovdqa LC1(%rip), %xmm6'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:1079:no such instruction: `vpcmpeqd %xmm5, %xmm5,%xmm5'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:1106:no such instruction: `vpxor (%rdx), %xmm5,%xmm3'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:1123:no such instruction: `vpxor (%rcx), %xmm3,%xmm4'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:1151:no such instruction: `vpsrlq $1, %xmm4,%xmm3'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:1178:no such instruction: `vpand %xmm4, %xmm3,%xmm2'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:1195:no such instruction: `vpxor %xmm4, %xmm3,%xmm1'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:1211:no such instruction: `vpor %xmm4, %xmm3,%xmm3'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:1230:no such instruction: `vmovdqa (%r8,%rax), %xmm0'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:1250:no such instruction: `vpxor %xmm5, %xmm3,%xmm3'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:1274:no such instruction: `vpand (%r9,%rax), %xmm0,%xmm0'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:1291:no such instruction: `vpxor %xmm5, %xmm0,%xmm0'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:1311:no such instruction: `vpor %xmm6, %xmm0,%xmm0'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:1328:no such instruction: `vpandn %xmm2, %xmm0,%xmm2'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:1344:no such instruction: `vmovd %xmm2, %rax'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:1360:no such instruction: `vpandn %xmm1, %xmm0,%xmm1'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:1376:no such instruction: `vpandn %xmm3, %xmm0,%xmm0'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:1395:no such instruction: `vpextrq $1, %xmm2,%rax'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:1420:no such instruction: `vmovd %xmm1, %rax'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:1434:no such instruction: `vpextrq $1, %xmm1,%rax'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:1459:no such instruction: `vmovd %xmm0, %rax'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:1473:no such instruction: `vpextrq $1, %xmm0,%rax'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:1590:no such instruction: `vmovdqa LC1(%rip), %xmm2'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:1620:no such instruction: `vpxor (%rdi), %xmm2,%xmm1'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:1633:no such instruction: `vpsrlq $1, %xmm1,%xmm0'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:1657:no such instruction: `vpor %xmm1, %xmm0,%xmm0'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:1675:no such instruction: `vmovaps %xmm0, (%r11,%rax)'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:1686:no such instruction: `vpxor -16(%rsi), %xmm2,%xmm1'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:1699:no such instruction: `vpsrlq $1, %xmm1,%xmm0'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:1713:no such instruction: `vpor %xmm1, %xmm0,%xmm0'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:1725:no such instruction: `vmovaps %xmm0, (%r14,%rax)'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:1901:no such instruction: `vmovdqa LC1(%rip), %xmm2'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:1916:no such instruction: `vpxor (%rdx), %xmm2,%xmm1'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:1929:no such instruction: `vpsrlq $1, %xmm1,%xmm0'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:1953:no such instruction: `vpor %xmm1, %xmm0,%xmm0'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:1970:no such instruction: `vmovaps %xmm0, (%r8,%rax)'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:1981:no such instruction: `vpxor -16(%r11), %xmm2,%xmm1'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:1994:no such instruction: `vpsrlq $1, %xmm1,%xmm0'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:2008:no such instruction: `vpor %xmm1, %xmm0,%xmm0'
/var/folders/gx/t1q6w73n4pn8jzfc4_k3lm0m0000gn/T//ccuBKQk1.s:2020:no such instruction: `vmovaps %xmm0, (%r9,%rax)'
make: *** [lib/darwin/libibs.dylib] Error 1
:nativeLib FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':nativeLib'.
> Process 'command 'make'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 12.99 secs
Johns-MacBook-Pro-7:hail farrell$

**Comment by cseed** [comment] 2017-01-20 19:53
Looks like we're not detecting the vector extensions supported by your CPU correctly.  Can you post the output of `c++ -v` and `sysctl -a | grep machdep.cpu`?

**Comment by jjfarrell** [comment] 2017-01-21 06:56
**c++ -v**
Using built-in specs.
COLLECT_GCC=c++
COLLECT_LTO_WRAPPER=/opt/local/libexec/gcc/x86_64-apple-darwin15/4.9.3/lto-wrapper
Target: x86_64-apple-darwin15
Configured with: /opt/local/var/macports/build/_opt_mports_dports_lang_gcc49/gcc49/work/gcc-4.9.3/configure --prefix=/opt/local --build=x86_64-apple-darwin15 --enable-languages=c,c++,objc,obj-c++,lto,fortran,java --libdir=/opt/local/lib/gcc49 --includedir=/opt/local/include/gcc49 --infodir=/opt/local/share/info --mandir=/opt/local/share/man --datarootdir=/opt/local/share/gcc-4.9 --with-local-prefix=/opt/local --with-system-zlib --disable-nls --program-suffix=-mp-4.9 --with-gxx-include-dir=/opt/local/include/gcc49/c++/ --with-gmp=/opt/local --with-mpfr=/opt/local --with-mpc=/opt/local --with-isl=/opt/local --disable-isl-version-check --with-cloog=/opt/local --disable-cloog-version-check --enable-stage1-checking --disable-multilib --enable-lto --enable-libstdcxx-time --with-as=/opt/local/bin/as --with-ld=/opt/local/bin/ld --with-ar=/opt/local/bin/ar --with-bugurl=https://trac.macports.org/newticket --with-pkgversion='MacPorts gcc49 4.9.3_0' --with-build-config=bootstrap-debug
Thread model: posix
gcc version 4.9.3 (MacPorts gcc49 4.9.3_0) 

 **sysctl -a | grep machdep.cpu**
machdep.cpu.tsc_ccc.denominator: 0
machdep.cpu.tsc_ccc.numerator: 0
machdep.cpu.thread_count: 8
machdep.cpu.core_count: 4
machdep.cpu.address_bits.virtual: 48
machdep.cpu.address_bits.physical: 36
machdep.cpu.tlb.shared: 512
machdep.cpu.tlb.data.large: 32
machdep.cpu.tlb.data.small: 64
machdep.cpu.tlb.inst.large: 8
machdep.cpu.tlb.inst.small: 64
machdep.cpu.cache.size: 256
machdep.cpu.cache.L2_associativity: 8
machdep.cpu.cache.linesize: 64
machdep.cpu.arch_perf.fixed_width: 48
machdep.cpu.arch_perf.fixed_number: 3
machdep.cpu.arch_perf.events: 0
machdep.cpu.arch_perf.events_number: 7
machdep.cpu.arch_perf.width: 48
machdep.cpu.arch_perf.number: 4
machdep.cpu.arch_perf.version: 3
machdep.cpu.xsave.extended_state1: 1 0 0 0
machdep.cpu.xsave.extended_state: 7 832 832 0
machdep.cpu.thermal.energy_policy: 0
machdep.cpu.thermal.hardware_feedback: 0
machdep.cpu.thermal.package_thermal_intr: 1
machdep.cpu.thermal.fine_grain_clock_mod: 1
machdep.cpu.thermal.core_power_limits: 1
machdep.cpu.thermal.ACNT_MCNT: 1
machdep.cpu.thermal.thresholds: 2
machdep.cpu.thermal.invariant_APIC_timer: 1
machdep.cpu.thermal.dynamic_acceleration: 1
machdep.cpu.thermal.sensor: 1
machdep.cpu.mwait.sub_Cstates: 135456
machdep.cpu.mwait.extensions: 3
machdep.cpu.mwait.linesize_max: 64
machdep.cpu.mwait.linesize_min: 64
machdep.cpu.processor_flag: 4
machdep.cpu.microcode_version: 21
machdep.cpu.cores_per_package: 8
machdep.cpu.logical_per_package: 16
machdep.cpu.extfeatures: SYSCALL XD EM64T LAHF RDTSCP TSCI
machdep.cpu.leaf7_features: SMEP ERMS RDWRFSGS
machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTES64 MON DSCPL VMX EST TM2 SSSE3 CX16 TPR PDCM SSE4.1 SSE4.2 x2APIC POPCNT AES PCID XSAVE OSXSAVE TSCTMR AVX1.0 RDRAND F16C
machdep.cpu.brand: 0
machdep.cpu.signature: 198313
machdep.cpu.extfeature_bits: 4967106816
machdep.cpu.leaf7_feature_bits: 641
machdep.cpu.feature_bits: 9203919201183202303
machdep.cpu.stepping: 9
machdep.cpu.extfamily: 0
machdep.cpu.extmodel: 3
machdep.cpu.model: 58
machdep.cpu.family: 6
machdep.cpu.brand_string: Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz
machdep.cpu.vendor: GenuineIntel
machdep.cpu.max_ext: 2147483656
machdep.cpu.max_basic: 13

**Comment by cseed** [comment] 2017-01-21 15:25
Thanks!  I'm guessing our code isn't compiling under gcc 4.9.  Can you try the Xcode-based c++?  That's what we're using.  In the meantime I'll try to reproduce this problem with gcc from MacPorts/brew.

**Comment by jjfarrell** [comment] 2017-01-21 23:47
Thanks! Moving over to the Xcode cc worked.

**cc --version**
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by jbloom22** [comment] 2017-01-26 15:24
@cseed can we close this?

**Comment by cseed** [comment] 2017-01-26 16:01
No, this should work with gcc.  I haven't had a chance to look at it yet.

**Comment by sa9** [comment] 2017-04-20 09:23
I am having the same error on Mac OS 10.12.4 with gcc 4.9.3.

How do I move over to Xcode cc?

**Comment by tpoterba** [comment] 2018-09-18 13:17
can anyone verify whether this is still a problem?

**Closed** 2020-04-14 12:01 UTC
Labels: deployment
