### ISSUE TITLE
Bad error when using  `annotate_cols` instead of `annotate_rows`

### ISSUE THREAD

**Issue by lfrancioli** [hail-is/hail#5415] opened 2019-02-22 16:25 UTC
To report a bug, fill in the information below. 
For support and feature requests, please use the discussion forum: http://discuss.hail.is/

-------------------------------------------------------------------------------------------

### What you did:

```
qc_ht = qc_mt.annotate_cols(
    dp_stats=hl.agg.group_by(qc_mt.qc_platform, hl.agg.stats(qc_mt.DP)),
    gq_stats=hl.agg.group_by(qc_mt.qc_platform, hl.agg.stats(qc_mt.GQ)),
    callstats=hl.agg.group_by(qc_mt.qc_platform, hl.agg.call_stats(qc_mt.GT, qc_mt.alleles)),
    call_rate=hl.agg.group_by(qc_mt.qc_platform, hl.agg.fraction(hl.is_defined(qc_mt.GQ)))
).rows()
```

### What went wrong (all error messages here, including the full java stack trace):

So I was distracted and used `annotate_rows` instead of `annotate_cols` and I got what seems to be an 0.1 error message:

```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-44-7491b514f674> in <module>
      3     gq_stats=hl.agg.group_by(qc_mt.qc_platform, hl.agg.stats(qc_mt.GQ)),
      4     callstats=hl.agg.group_by(qc_mt.qc_platform, hl.agg.call_stats(qc_mt.GT, qc_mt.alleles)),
----> 5     call_rate=hl.agg.group_by(qc_mt.qc_platform, hl.agg.fraction(hl.is_defined(qc_mt.GQ)))
      6 ).rows()
      7 # qc_ht = qc_ht.key_by('locus','alleles')

</opt/conda/lib/python3.6/site-packages/decorator.py:decorator-gen-976> in annotate_cols(self, **named_exprs)

/home/hail/hail.zip/hail/typecheck/check.py in wrapper(__original_func, *args, **kwargs)
    559     def wrapper(__original_func, *args, **kwargs):
    560         args_, kwargs_ = check_all(__original_func, args, kwargs, checkers, is_method=is_method)
--> 561         return __original_func(*args_, **kwargs_)
    562 
    563     return wrapper

/home/hail/hail.zip/hail/matrixtable.py in annotate_cols(self, **named_exprs)
    995         caller = "MatrixTable.annotate_cols"
    996         check_annotate_exprs(caller, named_exprs, self._col_indices)
--> 997         return self._select_cols(caller, self.col.annotate(**named_exprs))
    998 
    999     @typecheck_method(named_exprs=expr_any)

</opt/conda/lib/python3.6/site-packages/decorator.py:decorator-gen-1038> in _select_cols(self, caller, col, new_key)

/home/hail/hail.zip/hail/typecheck/check.py in wrapper(__original_func, *args, **kwargs)
    559     def wrapper(__original_func, *args, **kwargs):
    560         args_, kwargs_ = check_all(__original_func, args, kwargs, checkers, is_method=is_method)
--> 561         return __original_func(*args_, **kwargs_)
    562 
    563     return wrapper

/home/hail/hail.zip/hail/matrixtable.py in _select_cols(self, caller, col, new_key)
   3055         analyze(caller, col, self._col_indices, {self._row_axis})
   3056         base, cleanup = self._process_joins(col)
-> 3057         return cleanup(MatrixTable(MatrixMapCols(base._mir, col._ir, new_key)))
   3058 
   3059     @typecheck_method(caller=str, s=expr_struct())

/home/hail/hail.zip/hail/matrixtable.py in __init__(self, mir)
    556         self._entry_indices = Indices(self, {self._row_axis, self._col_axis})
    557 
--> 558         self._type = self._mir.typ
    559 
    560         self._global_type = self._type.global_type

/home/hail/hail.zip/hail/ir/base_ir.py in typ(self)
    106     def typ(self):
    107         if self._type is None:
--> 108             self._compute_type()
    109             assert self._type is not None, self
    110         return self._type

/home/hail/hail.zip/hail/ir/matrix_ir.py in _compute_type(self)
     81     def _compute_type(self):
     82         child_typ = self.child.typ
---> 83         self.new_col._compute_type(child_typ.col_env(), child_typ.entry_env())
     84         self._type = hl.tmatrix(
     85             child_typ.global_type,

/home/hail/hail.zip/hail/ir/ir.py in _compute_type(self, env, agg_env)
   1328         self.old._compute_type(env, agg_env)
   1329         for f, x in self.fields:
-> 1330             x._compute_type(env, agg_env)
   1331         self._type = self.old.typ._insert_fields(**{f: x.typ for f, x in self.fields})
   1332         if self.field_order:

/home/hail/hail.zip/hail/ir/ir.py in _compute_type(self, env, agg_env)
   1082     def _compute_type(self, env, agg_env):
   1083         self.key._compute_type(agg_env, None)
-> 1084         self.agg_ir._compute_type(env, agg_env)
   1085         self._type = tdict(self.key.typ, self.agg_ir.typ)
   1086 

/home/hail/hail.zip/hail/ir/ir.py in _compute_type(self, env, agg_env)
   1200         if self.init_op_args:
   1201             for a in self.init_op_args:
-> 1202                 a._compute_type(env, agg_env)
   1203         for a in self.seq_op_args:
   1204             a._compute_type(agg_env, None)

/home/hail/hail.zip/hail/ir/ir.py in _compute_type(self, env, agg_env)
    515 
    516     def _compute_type(self, env, agg_env):
--> 517         self.a._compute_type(env, agg_env)
    518         self._type = tint32
    519 

/home/hail/hail.zip/hail/ir/ir.py in _compute_type(self, env, agg_env)
   1359 
   1360     def _compute_type(self, env, agg_env):
-> 1361         self.o._compute_type(env, agg_env)
   1362         self._type = self.o.typ[self.name]
   1363 

/home/hail/hail.zip/hail/ir/ir.py in _compute_type(self, env, agg_env)
    351 
    352     def _compute_type(self, env, agg_env):
--> 353         assert self.name in env, f'{self.name} not found in {env}'
    354         self._type = env[self.name]
    355 

AssertionError: va not found in {'global': dtype('struct{qc_mt_params: struct{min_af: float64, min_callrate: float64, ld_r2: float64}}'), 'sa': dtype('struct{s: str, sample_callrate: float64, qc_platform: str}')}
```

**Comment by tpoterba** [comment] 2019-02-22 18:04
wait, isn't this a bug? Shouldn't these work?

**Comment by lfrancioli** [comment] 2019-02-22 18:45
Maybe... `qc_mt.qc_platform` is a col-field,  so the `group_by` would be pointless. Not sure if it would be a scoping issue or not.

**Comment by tpoterba** [comment] 2019-02-22 19:29
ah, this is actually a duplicate of #5240.

**Closed by tpoterba** 2019-02-22 19:29 UTC
Labels: bad error message
