### ISSUE TITLE
Print VEP stderr in error message if VEP fails

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#4767] opened 2018-11-13 16:47 UTC
will involve changes to RichIterator.pipe, probably.

**Comment by tpoterba** [comment] 2018-11-13 16:48
randomly assigned @jigold

**Comment by johnc1231** [comment] 2020-03-10 14:50
I think #8146 was essentially a duplicate of this, and #8150 resolved it.

**Closed by johnc1231** 2020-03-10 14:50 UTC
