### ISSUE TITLE
installing hail on Mac OS notebook 

### ISSUE THREAD

**Issue by ihelbig** [hail-is/hail#2062] opened 2017-08-02 05:25 UTC
I was able to install hail on my Macbook using a virtenv for python 2.7 and was able to import hail. 

However, when I want to create a hail context as outlined in the installation guide, I get the following message: 
``
Python 2.7.13 (default, Jul 18 2017, 09:16:53) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from hail import *
>>> hc = HailContext()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<decorator-gen-422>", line 2, in __init__
  File "/Users/ih/languages/hail.is/hail/python/hail/typecheck/check.py", line 226, in _typecheck
    return f(*args, **kwargs)
  File "/Users/ih/languages/hail.is/hail/python/hail/context.py", line 68, in __init__
    SparkContext._ensure_initialized()
  File "/Users/ih/hailenv/lib/python2.7/site-packages/pyspark/context.py", line 283, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/Users/ih/hailenv/lib/python2.7/site-packages/pyspark/java_gateway.py", line 77, in launch_gateway
    proc = Popen(command, stdin=PIPE, preexec_fn=preexec_func, env=env)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
``
Any idea what is going on with my installation, did somebody encounter this before already?

**Comment by cseed** [comment] 2017-08-02 13:35
It looks like it is failing when trying to start Java.  Do you have Java installed?  What version?  This is what I get on my mac:

```
$ java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
```

**Comment by ihelbig** [comment] 2017-08-02 13:40
I get the following version: 
``
$ java -version
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
``
I'm using virtualenv to run python 2.7 and I think I installed all the dependencies and python libraries that were required. Any further idea on what I can do to get this to work?

**Comment by tpoterba** [comment] 2017-08-02 13:41
What version of Spark / PySpark are you using?

**Comment by ihelbig** [comment] 2017-08-02 13:48
Spark/PySpark version 2.2.0, Scala version 2.11.8

**Comment by tpoterba** [comment] 2017-08-02 13:49
Ah. We haven't tested against Spark 2.2 yet, so that could be the issue. We currently test / deploy against 2.0.2 and 2.1.0, though I imagine we'll update these versions to 2.1.x and 2.2.x soon.

**Comment by tpoterba** [comment] 2017-08-02 13:50
I'm still at a loss as to the source of this specific error, though.

**Comment by cseed** [comment] 2017-08-02 15:08
@ihelbig Did you install through brew or pip?  Normally we recommend downloading the official Spark distribution.

@danking Did you install through brew?  Did you see anything like this?

/Users/ih/hailenv/lib/python2.7/site-packages/pyspark/java_gateway.py:77 is trying to start Spark by invoking $SPARK_HOME/bin/spark-submit.

What is $SPARK_HOME?

You might modify java_gateway.py before like 77 to print out `command` to see what command in detail it is trying to invoke.

**Comment by ihelbig** [comment] 2017-08-02 15:11
I used pip install - currently struggling to install the pyspark 2.0.2 version after downgrading to spark 2.0.2 

``$SPARK_HOME is /Users/ih/languages/spark-2.0.2-bin-hadoop2.7/bin``

**Comment by danking** [comment] 2017-08-02 15:15
Looks like there's an extra bin, no?

**Comment by danking** [comment] 2017-08-02 15:16
I use this:
```
dking@wmb16-359 # echo $SPARK_HOME
/Users/dking/borg/spark-2.0.2-bin-hadoop2.7/
```

**Comment by ihelbig** [comment] 2017-08-02 15:25
I removed the extra ``bin`` - when I run hc=HailContext(), I get the following: 

``>>> hc = HailContext()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<decorator-gen-422>", line 2, in __init__
  File "/Users/ih/languages/hail.is/hail/python/hail/typecheck/check.py", line 226, in _typecheck
    return f(*args, **kwargs)
  File "/Users/ih/languages/hail.is/hail/python/hail/context.py", line 83, in __init__
    parquet_compression, min_block_size, branching_factor, tmp_dir)
TypeError: 'JavaPackage' object is not callable``

I am realizing that pip still installs pyspark 2.2.0 - is this the issue?

**Comment by cseed** [comment] 2017-08-02 15:28
Yeah, no trailing bin.  I think we can sanity-check the SPARK_HOME setting in the HailContext constructor to give a more informative error message.

**Comment by tpoterba** [comment] 2017-08-02 15:30
Konrad and Beryl have seen this error before trying to use Spark 2.2:
http://discuss.hail.is/t/typeerror-javapackage-object-is-not-callable/250

**Comment by danking** [comment] 2017-08-02 15:32
And there's of course also the question of to what `SPARK_CLASSPATH` is set.

**Comment by tpoterba** [comment] 2017-08-02 15:35
`SPARK_CLASSPATH` is deprecated, maybe we should look at using `driverClassPath` as is now intended?

**Comment by ihelbig** [comment] 2017-08-02 15:44
``echo $SPARK_CLASSPATH
/Users/ih/languages/hail.is/hail/build/libs/hail-all-spark.jar``
SPARK_CLASSPATH is set correctly, however, I still get the error message
``>>> hc = HailContext()
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel).
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<decorator-gen-422>", line 2, in __init__
  File "/Users/ih/languages/hail.is/hail/python/hail/typecheck/check.py", line 226, in _typecheck
    return f(*args, **kwargs)
  File "/Users/ih/languages/hail.is/hail/python/hail/context.py", line 83, in __init__
    parquet_compression, min_block_size, branching_factor, tmp_dir)
TypeError: 'JavaPackage' object is not callable``

What do I need to do about the driverClassPath?

**Comment by tpoterba** [comment] 2017-08-02 15:50
Can you try running this before hail context creation:
```python
old_popen = subprocess.Popen

def wrapped(*args, **kwargs):
    print('args are: ' + str(args))
    print('kwargs are: ' + str(kwargs))
    return old_popen(*args, **kwargs)

subprocess.Popen = wrapped
```

**Comment by tpoterba** [comment] 2017-08-02 15:50
Then it should print out the command it's trying to run

**Comment by ihelbig** [comment] 2017-08-02 15:56
...stupid question (Python newby) - how do you want me to print this out? 
``pprint(subprocess.Popen)?``

**Comment by tpoterba** [comment] 2017-08-02 15:57
Sorry, should have clarified - the above code "monkey-patches" the subprocess Popen function so it prints before it runs. Just pop the code above your `hc = HailContext(...)`, everything else can remain unchanged.

**Comment by ihelbig** [comment] 2017-08-02 16:01
``>>> import subprocess``
``>>> old_popen = subprocess.Popen``
``>>> def wrapped(*args, **kwargs):``
``...     print('args are: ' + str(args))``
``...     print('kwargs are: ' + str(kwargs))``
``...     return old_popen(*args, **kwargs)``
``... ``
``>>> subprocess.Popen = wrapped``
``>>> hc = HailContext()``
``Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties``
``Setting default log level to "WARN".``
``To adjust logging level use sc.setLogLevel(newLevel).``
``Traceback (most recent call last):``
``  File "<stdin>", line 1, in <module>``
 `` File "<decorator-gen-422>", line 2, in __init__``
 `` File "/Users/ih/languages/hail.is/hail/python/hail/typecheck/check.py", line 226, in _typecheck
    return f(*args, **kwargs)``
 `` File "/Users/ih/languages/hail.is/hail/python/hail/context.py", line 83, in __init__
  parquet_compression, min_block_size, branching_factor, tmp_dir)``
``TypeError: 'JavaPackage' object is not callable``

Is this what you were suggesting or am I missing something?

**Comment by tpoterba** [comment] 2017-08-02 16:04
Oh, it looks like this error isn't from a subprocess call. The thing you added would help debug the first error you posted (No such file or directory) but not this one, it looks like.

**Comment by tpoterba** [comment] 2017-08-02 16:05
This is very weird. I suspect that there's some piece of Spark 2.2 that doesn't work with our current setup, and it's sneaking in even though SPARK_HOME is set to 2.0.2

**Comment by danking** [comment] 2017-08-02 16:05
@tpoterba looks like his issue is now with calling the hail library. I suspect the issue is now with `driverClassPath`.

**Comment by danking** [comment] 2017-08-02 16:07
Can you ensure you've set these two java options?
```
  --conf='spark.driver.extraClassPath=./hail.jar' \
  --conf='spark.executor.extraClassPath=./hail.jar'
```

I don't know if pyspark has a `--conf` option, but there should be some equivalent.

**Comment by ihelbig** [comment] 2017-08-02 16:14
...I would need a quick refresher if you don't mind- how do I set Java options?

**Comment by danking** [comment] 2017-08-02 17:43
Assuming you're using `pyspark` to start your spark session, I believe this will work:

```bash
pyspark --properties="spark.driver.extraClassPath=/Users/ih/languages/hail.is/hail/build/libs/hail-all-spark.jar,spark.executor.extraClassPath=./hail-all-spark.jar" --jars /Users/ih/languages/hail.is/hail/build/libs/hail-all-spark.jar
```

If that doesn't work for you, would you mind sharing the exact invocation string you're using?

**Comment by ihelbig** [comment] 2017-08-02 17:46
``$ pyspark --properties="spark.driver.extraClassPath=/Users/ih/languages/hail.is/hail/build/libs/hail-all-spark.jar,spark.executor.extraClassPath=./hail-all-spark.jar" --jars /Users/ih/languages/hail.is/hail/build/libs/hail-all-spark.jar
Exception in thread "main" java.lang.IllegalArgumentException: pyspark does not support any application options.
	at org.apache.spark.launcher.CommandBuilderUtils.checkArgument(CommandBuilderUtils.java:241)
	at org.apache.spark.launcher.SparkSubmitCommandBuilder.buildPySparkShellCommand(SparkSubmitCommandBuilder.java:290)
	at org.apache.spark.launcher.SparkSubmitCommandBuilder.buildCommand(SparkSubmitCommandBuilder.java:147)
	at org.apache.spark.launcher.Main.main(Main.java:86)``

It sounds like pyspark does not accept properties? -- This may seem like a stupid question, but do I need to start a spark session prior to invoking hail?

**Comment by ihelbig** [comment] 2017-08-02 17:58
Here is what I get when invoking pyspark

$ pyspark
Python 2.7.13 (default, Jul 18 2017, 09:16:53) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel).
17/08/02 13:56:47 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
17/08/02 13:56:47 WARN SparkConf: 
SPARK_CLASSPATH was detected (set to '/Users/ih/languages/hail.is/build/libs/hail-all-spark.jar').
This is deprecated in Spark 1.0+.

Please instead use:
 - ./spark-submit with --driver-class-path to augment the driver classpath
 - spark.executor.extraClassPath to augment the executor classpath
        
17/08/02 13:56:47 WARN SparkConf: Setting 'spark.executor.extraClassPath' to '/Users/ih/languages/hail.is/build/libs/hail-all-spark.jar' as a work-around.
17/08/02 13:56:47 WARN SparkConf: Setting 'spark.driver.extraClassPath' to '/Users/ih/languages/hail.is/build/libs/hail-all-spark.jar' as a work-around.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 2.0.2
      /_/

Using Python version 2.7.13 (default, Jul 18 2017 09:16:53)
SparkSession available as 'spark'

**Comment by ihelbig** [comment] 2017-08-04 03:54
I just wanted to let you know that the issue was fixed by running python through Jupyter notebook on my Mac where the HailContext could be created without problems. I never managed to run this through the command line, but as I wanted to use the notebook, anyway, this was ok for me. 

However, I encountered a problem within your tutorial with the 'data/1kg.vds', which throws a fatal error 
``HailException: Invalid VDS: old version [4]
  Recreate VDS with current version of Hail.``
However, as this is a separate problem, I'll open up a separate issue for this.

**Comment by ihelbig** [comment] 2017-08-04 04:08
...and now it also works nicely in the command line. 

Here is what my mistake was:

I started Hail from within hail/scripts folder by executing ./hail, which gave me an interactive shell within the python 2.7 context. This was apparently wrong. 

Initializing with `$python2.7` from within the terminal and then importing hail somehow did the trick. Don't know if this makes sense, but Hail is up and running now!

**Comment by danking** [comment] 2017-08-04 13:00
Regarding the `pyspark` issue, it looks like you have to use `--properties-file` and then put that comma-sepearted list as a newline-separated list in a file. That error message is pyspark's rather terrible way of telling you that it doesn't support a `--properties` option.

Regarding the old version of VDS, the `master` branch of hail is now an unstable development branch. If you want a consistent user experience with backwards compatible interfaces, please check out and exclusively use the `0.1` branch. Tim discusses the wider change [here](http://discuss.hail.is/t/deployment-changes-branching-off-for-faster-development/261/1). The VDS format will likely change on the scale of days on the `master` branch.

Regarding the `hail/scripts` folder, that is a repository of scripts that our build system uses as templates to create a pre-compiled, ready-to-go distribution that only requires a Spark installation. These distributions are available from the Google Storage API at gs://hail-common/distributions.

If you're building from source, I recommend following exactly the steps listed [here](https://hail.is/docs/stable/getting_started.html#building-hail-from-source) so as to avoid any future hiccups. NB: the steps for [Running Hail Locally](https://hail.is/docs/stable/getting_started.html#running-hail-locally) are for using the pre-compiled distribution, not for the result of building hail directly from source.

**Comment by danking** [comment] 2017-08-04 13:01
I'm going to close this issue, as it seems to be resolved. If this is not the case please feel free to re-open it!

**Closed by danking** 2017-08-04 13:01 UTC

**Comment by tpoterba** [comment] 2017-08-04 13:02
a downloadable link to the distributions can be found here: 
https://hail.is/docs/stable/getting_started.html

The current link for Spark 2.0.2 is https://storage.googleapis.com/hail-common/distributions/0.1/Hail-0.1-4238176-Spark-2.0.2.zip
