### ISSUE TITLE
import_table imports header as row when reading utf8 with bom

### ISSUE THREAD

**Issue by lfrancioli** [hail-is/hail#8395] opened 2020-03-30 20:59 UTC
So I just had the following situation: saved an Excel doc from a collaborator as CSV to the import it into hail. Running `hl.import_table` didn't return any error... but somehow the header was both correctly assigned as column names but also added as the first line. After some poking around, it turns out that the file encoding was UTF8 with BOM and that it somehow tripped `hl.import_table`. Same file works after re-encoding it as plain UTF8. 

Please include the full Hail version and as much detail as possible.
version 0.2.34-914bd8a10ca2
-----------------------------------------------------------------------------

**Comment by tpoterba** [comment] 2020-04-14 20:59
duplicate of #6342

**Closed by tpoterba** 2020-04-14 20:59 UTC
