### ISSUE TITLE
Reference genome annotation death

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#5371] opened 2019-02-15 18:22 UTC
Trying to annotate a table with a reference genome creates tons of temp files, and ultimately fails with errors like:
```
Mkdirs failed to create file:/tmp/hail.aHapwOHwB9LA (exists=false, cwd=file:/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1550247966765_0004/container_1550247966765_0004_02_000051)

at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:456)
    at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:441)
    at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:929)
    at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:910)
    at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:807)
    at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:796)
    at is.hail.utils.richUtils.RichHadoopConfiguration$.is$hail$utils$richUtils$RichHadoopConfiguration$$create$extension(RichHadoopConfiguration.scala:24)
    at is.hail.utils.richUtils.RichHadoopConfiguration$.writeFile$extension(RichHadoopConfiguration.scala:296)
    at is.hail.io.reference.FASTAReader$$anonfun$setup$1.apply(FASTAReader.scala:45)
    at is.hail.io.reference.FASTAReader$$anonfun$setup$1.apply(FASTAReader.scala:44)
    at is.hail.utils.package$.using(package.scala:587)
    at is.hail.utils.richUtils.RichHadoopConfiguration$.readFile$extension(RichHadoopConfiguration.scala:293)
    at is.hail.io.reference.FASTAReader$.setup(FASTAReader.scala:44)
    at is.hail.io.reference.FASTAReader$$anonfun$getLocalFastaFileName$1.apply(FASTAReader.scala:30)
    at is.hail.io.reference.FASTAReader$$anonfun$getLocalFastaFileName$1.apply(FASTAReader.scala:30)
    at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:901)
    at is.hail.io.reference.FASTAReader$.getLocalFastaFileName(FASTAReader.scala:30)
    at is.hail.io.reference.SerializableReferenceSequenceFile.value$lzycompute(FASTAReader.scala:18)
    at is.hail.io.reference.SerializableReferenceSequenceFile.value(FASTAReader.scala:17)
    at is.hail.io.reference.FASTAReader.<init>(FASTAReader.scala:77)
    at is.hail.variant.ReferenceGenome.addSequenceFromReader(ReferenceGenome.scala:354)
    at is.hail.codegen.generated.C2.method2(Unknown Source)
    at is.hail.codegen.generated.C2.apply(Unknown Source)
    at is.hail.codegen.generated.C2.apply(Unknown Source)
    at is.hail.expr.ir.TableFilter$$anonfun$execute$3.apply(TableIR.scala:286)
    at is.hail.expr.ir.TableFilter$$anonfun$execute$3.apply(TableIR.scala:286)
    at is.hail.expr.ir.TableValue$$anonfun$6.apply(TableValue.scala:54)
    at is.hail.expr.ir.TableValue$$anonfun$6.apply(TableValue.scala:54)
    at is.hail.rvd.RVD$$anonfun$filterWithContext$1$$anonfun$apply$9.apply(RVD.scala:448)
    at is.hail.rvd.RVD$$anonfun$filterWithContext$1$$anonfun$apply$9.apply(RVD.scala:447)
    at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:463)
    at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
    at is.hail.rvd.RVD$$anonfun$apply$25$$anon$3.hasNext(RVD.scala:1266)
    at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
    at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
    at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
    at is.hail.rvd.RVD$$anonfun$apply$25$$anon$3.hasNext(RVD.scala:1266)
    at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
    at is.hail.io.RichContextRDDRegionValue$$anonfun$boundary$extension$1$$anon$1.hasNext(RowStore.scala:1301)
    at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
    at scala.collection.Iterator$$anon$1.hasNext(Iterator.scala:1004)
    at is.hail.utils.richUtils.RichIterator$$anon$5.isValid(RichIterator.scala:22)
    at is.hail.utils.StagingIterator.isValid(FlipbookIterator.scala:48)
    at is.hail.utils.FlipbookIterator$$anon$9.setValue(FlipbookIterator.scala:327)
    at is.hail.utils.FlipbookIterator$$anon$9.<init>(FlipbookIterator.scala:344)
    at is.hail.utils.FlipbookIterator.leftJoinDistinct(FlipbookIterator.scala:323)
    at is.hail.annotations.OrderedRVIterator.leftJoinDistinct(OrderedRVIterator.scala:62)
    at is.hail.rvd.KeyedRVD$$anonfun$6.apply(KeyedRVD.scala:88)
    at is.hail.rvd.KeyedRVD$$anonfun$6.apply(KeyedRVD.scala:88)
    at is.hail.rvd.KeyedRVD$$anonfun$orderedJoinDistinct$1.apply(KeyedRVD.scala:98)
    at is.hail.rvd.KeyedRVD$$anonfun$orderedJoinDistinct$1.apply(KeyedRVD.scala:95)
    at is.hail.sparkextras.ContextRDD$$anonfun$czipPartitions$1$$anonfun$apply$34.apply(ContextRDD.scala:420)
    at is.hail.sparkextras.ContextRDD$$anonfun$czipPartitions$1$$anonfun$apply$34.apply(ContextRDD.scala:420)
    at is.hail.sparkextras.ContextRDD$$anonfun$cmapPartitionsWithIndex$1$$anonfun$apply$30$$anonfun$apply$31.apply(ContextRDD.scala:373)
    at is.hail.sparkextras.ContextRDD$$anonfun$cmapPartitionsWithIndex$1$$anonfun$apply$30$$anonfun$apply$31.apply(ContextRDD.scala:373)
    at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
    at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
    at is.hail.rvd.RVD$$anonfun$apply$25$$anon$3.hasNext(RVD.scala:1266)
    at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
    at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
    at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
    at is.hail.rvd.RVD$$anonfun$apply$25$$anon$3.hasNext(RVD.scala:1266)
    at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
    at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:461)
    at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
    at is.hail.rvd.RVD$$anonfun$apply$25$$anon$3.hasNext(RVD.scala:1266)
    at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
    at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
    at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
    at is.hail.rvd.RVD$$anonfun$apply$25$$anon$3.hasNext(RVD.scala:1266)
    at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
    at scala.collection.Iterator$class.foreach(Iterator.scala:893)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
    at is.hail.io.RichContextRDDRegionValue$.writeRowsPartition(RowStore.scala:1265)
    at is.hail.io.RichContextRDDRegionValue$$anonfun$writeRows$extension$1.apply(RowStore.scala:1315)
    at is.hail.io.RichContextRDDRegionValue$$anonfun$writeRows$extension$1.apply(RowStore.scala:1315)
    at is.hail.utils.richUtils.RichContextRDD$$anonfun$1.apply(RichContextRDD.scala:50)
    at is.hail.utils.richUtils.RichContextRDD$$anonfun$1.apply(RichContextRDD.scala:35)
    at is.hail.sparkextras.ContextRDD$$anonfun$cmapPartitionsWithIndex$1$$anonfun$apply$30.apply(ContextRDD.scala:373)
    at is.hail.sparkextras.ContextRDD$$anonfun$cmapPartitionsWithIndex$1$$anonfun$apply$30.apply(ContextRDD.scala:373)
    at is.hail.sparkextras.ContextRDD$$anonfun$run$1$$anonfun$apply$8.apply(ContextRDD.scala:153)
    at is.hail.sparkextras.ContextRDD$$anonfun$run$1$$anonfun$apply$8.apply(ContextRDD.scala:153)
    at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
    at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
    at scala.collection.Iterator$class.foreach(Iterator.scala:893)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
    at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
    at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
    at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
    at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
    at scala.collection.AbstractIterator.to(Iterator.scala:1336)
    at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
    at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1336)
    at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
    at scala.collection.AbstractIterator.toArray(Iterator.scala:1336)
    at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$13.apply(RDD.scala:936)
    at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$13.apply(RDD.scala:936)
    at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2069)
    at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2069)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
    at org.apache.spark.scheduler.Task.run(Task.scala:108)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by danking** [comment] 2019-02-15 18:24
should this be tagged high prioritY @tpoterba ?

**Comment by tpoterba** [comment] 2019-02-15 18:34
yeah probably

**Comment by danking** [comment] 2019-02-15 22:22
Downgrading from high priority to normal priority because konrad isn't actually blocked by this.

The issue is probably caused by hail downloading the FASTA file once per task. Consider:
```
import hail as hl
rg = hl.get_reference('GRCh38')
rg.add_sequence('gs://hail-common/references/Homo_sapiens_assembly38.fasta.gz',
                'gs://hail-common/references/Homo_sapiens_assembly38.fasta.fai')
ht = hl.read_table('gs://konradk/liftover_test/gnomad_exomes.ht')
ht.annotate(context=ht.locus.sequence_context(before=1, after=1))._force_count()
```

`gnomad_exomes.ht` has about 10000 partitions.

If you execute this on a 100 node cluster, you'll see that workers will have many copies of the FASTA file:

```
dking@dk-sw-sczv:~$ du -sh /tmp/hail.*/*.fasta
3.1G	/tmp/hail.iNLnbdai1pJe/00000.fasta
3.1G	/tmp/hail.Psc430xLLmdE/00000.fasta
3.1G	/tmp/hail.RNWZxuNSm6h2/00000.fasta
3.1G	/tmp/hail.rxwJfyieiIie/00000.fasta
3.1G	/tmp/hail.w79BrNc7RXOz/00000.fasta
3.1G	/tmp/hail.yqgUhdCe5I6I/00000.fasta
```

I think the issue is that a ReferenceGenome is allocated once per shipped JVM bytecode pack. A ReferenceGenome has a FASTAReader which has a SerializableReferenceSequenceFile. That roughly means we allocate one SerializableReferenceSequenceFile per-task. As the tasks:worker ratio gets large, this becomes infeasible. If we move the reference genome management to some broadcasted object, we can ensure it's once per-JVM (in fact one per-JVM for a whole slew of tasks).

I'll look into this more at some point soon.

**Comment by tpoterba** [comment] 2019-02-26 17:55
I'd also note that the reference genome serialization isn't cheap either, for GRCh38.

**Comment by tpoterba** [comment] 2019-03-26 09:52
I think this is still broken after Cotton's RG broadcast change. In fact, that may have introduced new bugs. The lazy broadcasting of RG could potentially interact poorly with the mutation that addSequence does.

**Comment by konradjk** [comment] 2019-03-26 13:45
Yeah, I think it may have gotten a little better (instead of major death, executors just quietly die, and I have to add more in order to finish the run), but not by much.

**Comment by danking** [comment] 2019-06-27 14:05
@tpoterba @konradjk  Is this still a problem?

**Comment by danking** [comment] 2019-06-27 14:05
reopen if yes

**Comment by tpoterba** [comment] 2019-06-27 14:06
yes

**Comment by danking** [comment] 2020-07-14 15:27
@cseed 

Do your changes to byte code emission provide a path to using a broadcasted object for this instead of shipping it once per serialized task?

**Comment by chrisvittal** [comment] 2020-09-11 03:30
#9435 may at long last, finally be a solution to this.

We currently keep a static map per jvm that maps general FASTA paths to a local fasta path that we copy the FASTA into. My change serializes the downloading of these files (using a lock), and we never remove keys from the map, so we should finally have 1 FASTA file per executor. There are still circumstances that can blow up on us like restarting executors (like when yarn shuts them down) and then starts them up again. The broadcast changes fixed some of the issues, and I hope that my change can finally fix this.

**Comment by chrisvittal** [comment] 2020-09-19 17:47
Closing this for now. Will reopen if there is still an issue.

**Closed by chrisvittal** 2020-09-19 17:47 UTC
Labels: bug
