### ISSUE TITLE
hc.import_table(..)  min_partitions arg doesn't work as expected

### ISSUE THREAD

**Issue by bw2** [hail-is/hail#2420] opened 2017-11-12 03:38 UTC
To report a bug, fill in the information below. 
For support and feature requests, please use the discussion forum: http://discuss.hail.is/

-------------------------------------------------------------------------------------------

### What you did:  

kt = hc.import_table(["gnomad_coverage_chr1.tsv", "gnomad_coverage_chr2.tsv", ..], min_partitions=10000)

### What went wrong (all error messages here, including the full java stack trace):

I expected the behavior with min_partitions=10000 to be the same as calling repartition(10000), but the keytable only had # of partitions = # of input .tsv files. I switched to just calling repartition(10000) after importing, and it works as expected. 

May be duplicate of #508

**Comment by tpoterba** [comment] 2018-09-18 13:02
yeah, duplicate of #508

**Closed** 2018-09-18 13:02 UTC
