### ISSUE TITLE
artifacts incorrect

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#4514] opened 2018-10-09 23:51 UTC
The build failed but artifacts page reports all green.

See: https://storage.googleapis.com/hail-ci-0-1/ci/3076082248b28eb26ff38014b9cedad20c7d689a/414f3f183bd5f2ec04e1c732522cbc0b8b1fca31/artifacts/index.html

copied to gs://hail-cseed/bad-artifacts in case that gets overwritten.

**Comment by tpoterba** [comment] 2018-10-10 01:34
what failed?

**Comment by tpoterba** [comment] 2018-10-10 01:35
I need to see the index page (with the build log) to try to fix this. Everything on that page is rightfully green

**Comment by cseed** [comment] 2018-10-10 01:53
The PR failed: https://github.com/hail-is/hail/pull/4509 and the build log shows failed exit code 2: https://storage.googleapis.com/hail-ci-0-1/ci/7aa524504b8bafe0a4af859e73bc4f9efdaa052c/414f3f183bd5f2ec04e1c732522cbc0b8b1fca31/job-log

**Comment by tpoterba** [comment] 2018-10-10 13:04
I guess the design of the whole artifacts system doesn't really account for anything but hail/hail. We need to fix up the index page to account for other projects and add another level of testing indirection

**Comment by danking** [comment] 2018-10-22 21:37
@tpoterba should this be closed? I think you've resolved and moved to a different system.

**Comment by tpoterba** [comment] 2018-11-01 16:39
this isn't fixed, no. The problem isn't the hail/hail artifacts, but everything else.

**Comment by tpoterba** [comment] 2018-11-08 19:15
I'm unassigning myself after our Zulip discussion on the intended job dependency graph in batch.

**Comment by danking** [comment] 2019-01-04 17:34
I'm closing because this ticket merely notes that the artifact page is only representative of hail. This is expected behavior. The build log is the source of truth, the artifact page is only helpful for the `hail` subproject. In the future, the CI can define a DAG of jobs for the different subproject. The associated UI will enable users to quickly see what failed.

**Closed** 2019-01-04 17:34 UTC
Labels: bug, ci
